---
incompatible:
functional:
  - требование 1 Пользователь должен иметь возможность искать товары по ключевому слову.
  - требование 2 Пользователь должен иметь возможность искать товары по производителю.
  - требование 3 Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру.
  - требование 4 Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - требование 5 Пользователь должен иметь возможность добавлять товары в корзину (удалять) и просматривать содержимое корзины.
  - требование 6 Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - требование 7 Пользователь должен иметь возможность выбора языка

non-functional:    
  - требование 1 Сайт должен иметь мобильную версию.
  - требование 2 Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - требование 3 Сайт должен быть способен обрабатывать большое количество трафика
  - требование 4 Сайт должен быть безопасным и защищать данные пользователя.
implicit:
  - требование 1 Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - требование 2 Сайт должен быть безопасным и защищать данные пользователя.
  - требование 3 Описание товаров не противоречит закону.
